#!/usr/bin/env python3
"""Offline publication-boundary checks and reproducible, allowlisted ZIP export."""
import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import subprocess
import zipfile

ROOT = Path(__file__).resolve().parents[1]


def public_files(root):
    value = json.loads((root / 'public-files.json').read_text())
    if not isinstance(value, list) or not value or any(not isinstance(x, str) for x in value):
        raise ValueError('public-files.json must be a nonempty string array')
    if value != sorted(set(value)):
        raise ValueError('Public paths must be sorted and unique')
    for name in value:
        path = PurePosixPath(name)
        if (path.is_absolute() or str(path) != name or '..' in path.parts or
                not re.fullmatch(r'[A-Za-z0-9_./-]+', name) or
                path.parts[0] in {'lab', '.git', 'dist', 'node_modules', 'credentials', 'secrets'} or
                path.name.startswith('.env') or path.suffix in {'.jsonl', '.ndjson', '.key', '.pem', '.log'}):
            raise ValueError('Unsafe public path: ' + name)
    return value


def ignore_text(names):
    dirs = set()
    for name in names:
        for parent in PurePosixPath(name).parents:
            if str(parent) != '.':
                dirs.add(str(parent))
    return ('# Generated by scripts/package.py --sync-ignore. Review public-files.json first.\n'
            '# Default-deny publication: private labs and historical working files stay local.\n/*\n' +
            ''.join('!/' + d + '/\n/' + d + '/*\n' for d in sorted(dirs, key=lambda d: (d.count('/'), d))) +
            ''.join('!/' + name + '\n' for name in names))


def validate(root):
    root = root.resolve()
    names = public_files(root)
    allowed = set(names)
    for name in names:
        path = root / name
        if not path.is_file() or any(p.is_symlink() for p in [path, *path.parents] if p != root.parent):
            raise ValueError('Missing file or symlink: ' + name)
        if root not in path.resolve().parents:
            raise ValueError('Path leaves package: ' + name)
        for var in ('OPENROUTER_API_KEY', 'ANTHROPIC_API_KEY', 'ANTHROPIC_AUTH_TOKEN', 'CLAUDE_CODE_OAUTH_TOKEN', 'GH_TOKEN', 'GITHUB_TOKEN'):
            secret = os.environ.get(var, '').encode()
            if len(secret) >= 8 and secret in path.read_bytes():
                raise ValueError('Environment credential found in public file: ' + name)
    if (root / '.gitignore').read_text() != ignore_text(names):
        raise ValueError('Run --sync-ignore after reviewing the public list')
    load = lambda name: json.loads((root / name).read_text())
    manifest = load('.claude-plugin/plugin.json')
    marketplace = load('.claude-plugin/marketplace.json')
    package = load('package.json')
    entry = marketplace['plugins'][0]
    if not (len(marketplace['plugins']) == 1 and manifest['name'] == package['name'] == entry['name'] == 'jevshift' and
            marketplace['name'] == 'jevshift' and entry['source'] == './' and
            manifest['version'] == entry['version'] == package['version'] and
            re.fullmatch(r'\d+\.\d+\.\d+(?:-[a-z0-9.]+)?', manifest['version']) and
            manifest['license'] == entry['license'] == package['license'] == 'MIT' and package['private'] is True):
        raise ValueError('Manifest/version/license mismatch')
    options = manifest['userConfig']
    if not (options['openrouter_api_key']['sensitive'] is True and not options['openrouter_api_key'].get('default') and
            options['use_environment_key']['default'] is False and options['experimental_auto']['default'] is False):
        raise ValueError('Unsafe default evaluator configuration')
    if load('hooks/hooks.json') != {'modules': ['./register.ts']}:
        raise ValueError('Unexpected hook entry')
    for name in names:
        if name.endswith('.ts'):
            for target in re.findall(r'(?:from\s+|import\s*)[\'"](\.[^\'"]+)[\'"]', (root / name).read_text()):
                path = ((root / name).parent / target).resolve()
                if not path.is_relative_to(root) or path.relative_to(root).as_posix() not in allowed:
                    raise ValueError('Import outside public set: ' + name)
        if name.endswith('.md'):
            for target in re.findall(r'\]\(([^\s)]+)\)', (root / name).read_text()):
                if re.match(r'[a-z]+:', target) or target.startswith('#'):
                    continue
                path = ((root / name).parent / target.split('#')[0]).resolve()
                if not path.is_relative_to(root) or path.relative_to(root).as_posix() not in allowed:
                    raise ValueError('Broken public link: ' + name + ' -> ' + target)
    example = load('examples/jev-request.json')
    if example.get('model') != 'typesafe/jev-1.13' or list(example.get('questions', {})) != ['model_choice'] or not isinstance(example.get('state'), str):
        raise ValueError('Unexpected request example')
    # An ignore rule cannot protect a file that is already tracked.
    try:
        top = subprocess.run(['git', '-C', str(root), 'rev-parse', '--show-toplevel'], capture_output=True, text=True)
        if top.returncode == 0 and Path(top.stdout.strip()).resolve() == root:
            tracked = subprocess.run(['git', '-C', str(root), 'ls-files', '-z'], capture_output=True, check=True).stdout.decode().split('\0')
            if any(name and name not in allowed for name in tracked):
                raise ValueError('Tracked files outside public set; review before publication')
    except FileNotFoundError:
        pass
    return names


def build(root, output):
    names = validate(root)
    version = json.loads((root / '.claude-plugin/plugin.json').read_text())['version']
    output = output.resolve()
    if output.exists():
        raise ValueError('Refusing to overwrite output directory')
    output.mkdir(parents=True)
    archive = output / ('jevshift-' + version + '.zip')
    inventory = {}
    with zipfile.ZipFile(archive, 'x', compression=zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for name in names:
            data = (root / name).read_bytes()
            inventory[name] = hashlib.sha256(data).hexdigest()
            info = zipfile.ZipInfo('jevshift/' + name, (2026, 1, 1, 0, 0, 0))
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(info, data)
    result = {'version': version, 'fileCount': len(names), 'files': inventory,
              'archive': archive.name, 'sha256': hashlib.sha256(archive.read_bytes()).hexdigest()}
    (output / 'SHA256SUMS.json').write_text(json.dumps(result, indent=2) + '\n')
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--sync-ignore', action='store_true')
    parser.add_argument('--output', type=Path)
    args = parser.parse_args()
    if args.sync_ignore:
        (ROOT / '.gitignore').write_text(ignore_text(public_files(ROOT)))
    if args.output:
        result = build(ROOT, args.output)
        print(json.dumps({k: v for k, v in result.items() if k != 'files'}, indent=2))
    else:
        print('Public package verified: ' + str(len(validate(ROOT))) + ' files; no network call.')


if __name__ == '__main__':
    main()
